# This is a basic workflow to help you get started with Actions

name: Integration Test on Azure DevTest Labs 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - feature/azure-devtest-labs-arm-CICD
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-integration-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Login to Azure
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_DEV_TEST_LABS_CREDENTIALS }}'

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        #azcliversion: 2.0.72
        inlineScript: |
          az version | jq '.'
          az account show | jq '.'

      # # Once logged into Azure, run a test command to check it worked
      # - name: Azure CLI script
      #   uses: azure/CLI@v1
      #   with:
      #     # This is the version with the fix for creating a DevTest lab
      #     azcliversion: 2.24.0
      #     inlineScript: |
      #       az account show


      # # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
